---
title: "Tidyverse"
author: "Jeevan Kumar Hemasunder Latha"
---



Add a language to syntax highlight code blocks:
#Loading Libraries
```{r}
library(tidyverse)
library(tibble)
library(readr)
library(dplyr)
library(magrittr)
library(tidyr)
library(stringr)
library(ggplot2)
library(readxl)
library(lubridate)
```
#Read Data
```{r}
bikes_tbl <- read_excel(path ="C:/Users/Jeevan/OneDrive/Documents/TUHH/Business/ss23-bdsb-Jeevankumarhl/assets/ds_data_assets/bikes.xlsx")
orderlines_tbl <- read_excel(path = "C:/Users/Jeevan/OneDrive/Documents/TUHH/Business/ss23-bdsb-Jeevankumarhl/assets/ds_data_assets/orderlines.xlsx")
bikeshops_tbl  <- read_excel("C:/Users/Jeevan/OneDrive/Documents/TUHH/Business/ss23-bdsb-Jeevankumarhl/assets/ds_data_assets/bikeshops.xlsx")
```
#Joining the tables
```{r}
left_join(orderlines_tbl, bikes_tbl, by = c("product.id" = "bike.id"))

bike_orderlines_joined_tbl   <-   orderlines_tbl   %>%
  left_join(bikes_tbl, by = c("product.id" = "bike.id"))  %>%
  left_join(bikeshops_tbl, by = c("customer.id" = "bikeshop.id"))

#glimpse(bike_orderlines_joined_tbl)
```

#Finding City name from location 
```{r}
bike_orderlines_wrangled_tbl <- bike_orderlines_joined_tbl %>% 
 separate(col = location,
           into = c("city","state"),
           sep = ", ",
           convert = T) %>%
  separate(col    = category,
           into   = c("category.1", "category.2", "category.3"),
           sep    = " - ") %>%
  
  
  mutate(total_price = price * quantity)
```

#State with Highest Revenue and Graph
```{r}
sales_by_location_tbl  <-  bike_orderlines_wrangled_tbl %>%
  select(state, total_price) %>%
  group_by(state) %>%
  summarize(sales = sum(total_price)) %>%
  mutate(sales_text = scales::dollar(sales, big.mark = ".",
                                     decimal.mark = ",",
                                     prefix = "",
                                     suffix = "€"))


glimpse(sales_by_location_tbl)

# ADD THIS IN THE WEBSITE WHILE ADDING THE SCRIPT{r plot, fig.width=10, fig.height=7}

sales_by_location_tbl %>%
  ggplot(aes(x = state, y = sales)) +
  
  geom_col(fill = "#2DC6D6") +
  geom_label(aes(label = sales_text)) +
  #geom_smooth(method = "lm", se = FALSE)+
  scale_y_continuous( labels = scales::dollar_format(big.mark = ".",
                                                     decimal.mark = ",",
                                                     prefix = "",
                                                     suffix = " €")) +
  
  labs(
    title = "Revenue by Location(State)",
    subtitle = "Trend",   #North Rhine-Westphalia has the highest revenue.
    x = "",
    y = "Revenue"
  ) + theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

# Analyze the sales by location and year (facet_wrap)
```{r}

sales_by_location_cat_1_tbl <- bike_orderlines_wrangled_tbl %>%
  select(state, total_price, category.1) %>%
  group_by(state, category.1) %>%
  summarise(sales = sum(total_price)) %>%
  ungroup() %>%
  mutate(sales_text = scales::dollar(sales, big.mark = ".", 
                                     decimal.mark = ",", 
                                     prefix = "", 
                                     suffix = " €"))

#sales_by_location_cat_1_tbl
sales_by_location_cat_1_tbl %>%
  ggplot(aes(x = category.1, y = sales, fill = state)) +
  geom_col() +
  facet_wrap(~ state) +
  scale_y_continuous(labels = scales::dollar_format(big.mark = ".", 
                                                    decimal.mark = ",", 
                                                    prefix = "", 
                                                    suffix = " €")) +
  labs(
    title = "Revenue by category and state",
    subtitle = "Trend in sales of products in each state",
    fill = "State List"
  )+ theme(axis.text.x = element_text(angle = 45, hjust = 1))
  
```